import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Workshop - Admin",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="px-2">
            <h1>Admin Layout</h1>
            {children}
        </div>
    );
}
