import type { Metadata } from "next";
import LogoutButton from "./components/LogoutButton";

export const metadata: Metadata = {
    title: "Workshop - Admin",
    description: "Generated by create next app",
};

export default async function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div className="px-2">
            <h1>Admin Layout</h1>
            <LogoutButton />
            {children}
        </div>
    );
}
