import { Metadata } from 'next';
import PostClient from '../components/PostClient';

export const metadata: Metadata = {
  title: "Workshop - Post-Client",
  description: "Generated by create next app",
};

export default function PostPage() {

  return (
    <div>
      <PostClient />
    </div>
  )
}
