import { Metadata } from 'next';
import Link from 'next/link';
import React from 'react'

export const metadata: Metadata = {
  title: "Workshop - Post",
  description: "Generated by create next app",
};
//type

interface Post {
  userId: number
  id: number
  title: string
  body: string
}

//Server Side Fetching
async function getData() {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=6');
  return response.json();
}

export default async function PostPage() {

  const data = await getData();
  console.log(data);

  return (
    <div>
      <h1 className='text-3xl my-2'>Post Page</h1>
      <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2'>
        {data.map((post: Post) => (
          <div key={post.id} className='px-4 py-6 border-1 flex flex-col'>
            <h1>{post.id}</h1>
            <h1 className='text-xl'>{post.title}</h1>
            <Link href={`/post/${post.id}`} className='px-2 py-3 border-1 mt-4'>อ่านเพิ่ม...</Link>
          </div>
        ))}
      </div>
    </div>
  )
}
