import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Workshop - Post",
  description: "Generated by create next app",
};

export default function PostPage() {
  return (
    <div>
        <h1 className='text-3xl'>Post Page</h1>
    </div>
  )
}
